// RPC functions for DTB
// created: 10.06.2016 12:20:05
// This is an auto generated file
// *** DO NOT EDIT THIS FILE ***

#include "pixel_dtb.h"
const char rpc_timestamp[] = "10.06.2016 12:20:05";

extern CRpcError rpc_error;
extern CTestboard tb;

bool rpc__GetRpcVersion$S(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	uint16_t rpc_par0 = tb.GetRpcVersion();
	msg.CreateCmd(0);
	msg.Put_UINT16(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__GetRpcCallId$i3c(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	string rpc_par1; if (!msg.RecvString(rpc_par1)) return false;
	int32_t rpc_par0 = tb.GetRpcCallId(rpc_par1);
	msg.CreateCmd(1);
	msg.Put_INT32(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__GetRpcTimestamp$v4c(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	uint32_t rpc_par1_hdr;
	stringR rpc_par1;
	tb.GetRpcTimestamp(rpc_par1);
	msg.CreateCmd(2);
	if (!msg.SendCmd()) return false;
	if (!msg.SendString(rpc_par1_hdr, rpc_par1)) return false;
	msg.Flush();
	return true;
}

bool rpc__GetRpcCallCount$i(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	int32_t rpc_par0 = tb.GetRpcCallCount();
	msg.CreateCmd(3);
	msg.Put_INT32(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__GetRpcCallName$bi4c(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(4)) return false;
	int32_t rpc_par1 = msg.Get_INT32();
	uint32_t rpc_par2_hdr;
	stringR rpc_par2;
	bool rpc_par0 = tb.GetRpcCallName(rpc_par1,rpc_par2);
	msg.CreateCmd(4);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	if (!msg.SendString(rpc_par2_hdr, rpc_par2)) return false;
	msg.Flush();
	return true;
}

bool rpc__GetRpcCallHash$I(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	uint32_t rpc_par0 = tb.GetRpcCallHash();
	msg.CreateCmd(5);
	msg.Put_UINT32(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__GetInfo$v4c(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	uint32_t rpc_par1_hdr;
	stringR rpc_par1;
	tb.GetInfo(rpc_par1);
	msg.CreateCmd(6);
	if (!msg.SendCmd()) return false;
	if (!msg.SendString(rpc_par1_hdr, rpc_par1)) return false;
	msg.Flush();
	return true;
}

bool rpc__GetBoardId$S(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	uint16_t rpc_par0 = tb.GetBoardId();
	msg.CreateCmd(7);
	msg.Put_UINT16(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__GetHWVersion$v4c(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	uint32_t rpc_par1_hdr;
	stringR rpc_par1;
	tb.GetHWVersion(rpc_par1);
	msg.CreateCmd(8);
	if (!msg.SendCmd()) return false;
	if (!msg.SendString(rpc_par1_hdr, rpc_par1)) return false;
	msg.Flush();
	return true;
}

bool rpc__GetFWVersion$S(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	uint16_t rpc_par0 = tb.GetFWVersion();
	msg.CreateCmd(9);
	msg.Put_UINT16(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__GetSWVersion$S(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	uint16_t rpc_par0 = tb.GetSWVersion();
	msg.CreateCmd(10);
	msg.Put_UINT16(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__UpgradeGetVersion$S(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	uint16_t rpc_par0 = tb.UpgradeGetVersion();
	msg.CreateCmd(11);
	msg.Put_UINT16(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__UpgradeStart$CS(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint16_t rpc_par1 = msg.Get_UINT16();
	uint8_t rpc_par0 = tb.UpgradeStart(rpc_par1);
	msg.CreateCmd(12);
	msg.Put_UINT8(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__UpgradeData$C3c(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	string rpc_par1; if (!msg.RecvString(rpc_par1)) return false;
	uint8_t rpc_par0 = tb.UpgradeData(rpc_par1);
	msg.CreateCmd(13);
	msg.Put_UINT8(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__UpgradeError$C(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	uint8_t rpc_par0 = tb.UpgradeError();
	msg.CreateCmd(14);
	msg.Put_UINT8(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__UpgradeErrorMsg$v4c(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	uint32_t rpc_par1_hdr;
	stringR rpc_par1;
	tb.UpgradeErrorMsg(rpc_par1);
	msg.CreateCmd(15);
	if (!msg.SendCmd()) return false;
	if (!msg.SendString(rpc_par1_hdr, rpc_par1)) return false;
	msg.Flush();
	return true;
}

bool rpc__UpgradeExec$vS(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint16_t rpc_par1 = msg.Get_UINT16();
	tb.UpgradeExec(rpc_par1);
	return true;
}

bool rpc__Init$v(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	tb.Init();
	return true;
}

bool rpc__Welcome$v(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	tb.Welcome();
	return true;
}

bool rpc__SetLed$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.SetLed(rpc_par1);
	return true;
}

bool rpc__cDelay$vS(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint16_t rpc_par1 = msg.Get_UINT16();
	tb.cDelay(rpc_par1);
	return true;
}

bool rpc__uDelay$vS(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint16_t rpc_par1 = msg.Get_UINT16();
	tb.uDelay(rpc_par1);
	return true;
}

bool rpc__SetClockSource$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.SetClockSource(rpc_par1);
	return true;
}

bool rpc__IsClockPresent$b(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	bool rpc_par0 = tb.IsClockPresent();
	msg.CreateCmd(23);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__SetClock$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.SetClock(rpc_par1);
	return true;
}

bool rpc__SetClockStretch$vCSS(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(5)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint16_t rpc_par2 = msg.Get_UINT16();
	uint16_t rpc_par3 = msg.Get_UINT16();
	tb.SetClockStretch(rpc_par1,rpc_par2,rpc_par3);
	return true;
}

bool rpc__Sig_SetMode$vCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	tb.Sig_SetMode(rpc_par1,rpc_par2);
	return true;
}

bool rpc__Sig_SetPRBS$vCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	tb.Sig_SetPRBS(rpc_par1,rpc_par2);
	return true;
}

bool rpc__Sig_SetDelay$vCSc(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(4)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint16_t rpc_par2 = msg.Get_UINT16();
	int8_t rpc_par3 = msg.Get_INT8();
	tb.Sig_SetDelay(rpc_par1,rpc_par2,rpc_par3);
	return true;
}

bool rpc__Sig_SetLevel$vCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	tb.Sig_SetLevel(rpc_par1,rpc_par2);
	return true;
}

bool rpc__Sig_SetOffset$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.Sig_SetOffset(rpc_par1);
	return true;
}

bool rpc__Sig_SetLVDS$v(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	tb.Sig_SetLVDS();
	return true;
}

bool rpc__Sig_SetLCDS$v(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	tb.Sig_SetLCDS();
	return true;
}

bool rpc__Sig_SetRdaToutDelay$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.Sig_SetRdaToutDelay(rpc_par1);
	return true;
}

bool rpc__SignalProbeD1$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.SignalProbeD1(rpc_par1);
	return true;
}

bool rpc__SignalProbeD2$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.SignalProbeD2(rpc_par1);
	return true;
}

bool rpc__SignalProbeDeserD1$vCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	tb.SignalProbeDeserD1(rpc_par1,rpc_par2);
	return true;
}

bool rpc__SignalProbeDeserD2$vCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	tb.SignalProbeDeserD2(rpc_par1,rpc_par2);
	return true;
}

bool rpc__SignalProbeA1$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.SignalProbeA1(rpc_par1);
	return true;
}

bool rpc__SignalProbeA2$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.SignalProbeA2(rpc_par1);
	return true;
}

bool rpc__SignalProbeADC$vCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	tb.SignalProbeADC(rpc_par1,rpc_par2);
	return true;
}

bool rpc__Pon$v(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	tb.Pon();
	return true;
}

bool rpc__Poff$v(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	tb.Poff();
	return true;
}

bool rpc___SetVD$vS(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint16_t rpc_par1 = msg.Get_UINT16();
	tb._SetVD(rpc_par1);
	return true;
}

bool rpc___SetVA$vS(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint16_t rpc_par1 = msg.Get_UINT16();
	tb._SetVA(rpc_par1);
	return true;
}

bool rpc___SetID$vS(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint16_t rpc_par1 = msg.Get_UINT16();
	tb._SetID(rpc_par1);
	return true;
}

bool rpc___SetIA$vS(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint16_t rpc_par1 = msg.Get_UINT16();
	tb._SetIA(rpc_par1);
	return true;
}

bool rpc___GetVD$S(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	uint16_t rpc_par0 = tb._GetVD();
	msg.CreateCmd(47);
	msg.Put_UINT16(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc___GetVA$S(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	uint16_t rpc_par0 = tb._GetVA();
	msg.CreateCmd(48);
	msg.Put_UINT16(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc___GetID$S(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	uint16_t rpc_par0 = tb._GetID();
	msg.CreateCmd(49);
	msg.Put_UINT16(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc___GetIA$S(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	uint16_t rpc_par0 = tb._GetIA();
	msg.CreateCmd(50);
	msg.Put_UINT16(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc___GetVD_Reg$S(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	uint16_t rpc_par0 = tb._GetVD_Reg();
	msg.CreateCmd(51);
	msg.Put_UINT16(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc___GetVDAC_Reg$S(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	uint16_t rpc_par0 = tb._GetVDAC_Reg();
	msg.CreateCmd(52);
	msg.Put_UINT16(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc___GetVD_Cap$S(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	uint16_t rpc_par0 = tb._GetVD_Cap();
	msg.CreateCmd(53);
	msg.Put_UINT16(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__HVon$v(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	tb.HVon();
	return true;
}

bool rpc__HVoff$v(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	tb.HVoff();
	return true;
}

bool rpc__ResetOn$v(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	tb.ResetOn();
	return true;
}

bool rpc__ResetOff$v(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	tb.ResetOff();
	return true;
}

bool rpc__GetStatus$C(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	uint8_t rpc_par0 = tb.GetStatus();
	msg.CreateCmd(58);
	msg.Put_UINT8(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__SetRocAddress$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.SetRocAddress(rpc_par1);
	return true;
}

bool rpc__Pg_SetCmd$vSS(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(4)) return false;
	uint16_t rpc_par1 = msg.Get_UINT16();
	uint16_t rpc_par2 = msg.Get_UINT16();
	tb.Pg_SetCmd(rpc_par1,rpc_par2);
	return true;
}

bool rpc__Pg_SetCmdAll$v1S(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	vector<uint16_t> rpc_par1; if (!rpc_RecvVector(msg, rpc_par1)) return false;
	tb.Pg_SetCmdAll(rpc_par1);
	return true;
}

bool rpc__Pg_SetSum$vS(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint16_t rpc_par1 = msg.Get_UINT16();
	tb.Pg_SetSum(rpc_par1);
	return true;
}

bool rpc__Pg_Stop$v(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	tb.Pg_Stop();
	return true;
}

bool rpc__Pg_Single$v(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	tb.Pg_Single();
	return true;
}

bool rpc__Pg_Trigger$v(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	tb.Pg_Trigger();
	return true;
}

bool rpc__Pg_Triggers$vIS(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(6)) return false;
	uint32_t rpc_par1 = msg.Get_UINT32();
	uint16_t rpc_par2 = msg.Get_UINT16();
	tb.Pg_Triggers(rpc_par1,rpc_par2);
	return true;
}

bool rpc__Pg_Loop$vS(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint16_t rpc_par1 = msg.Get_UINT16();
	tb.Pg_Loop(rpc_par1);
	return true;
}

bool rpc__Trigger_Select$vS(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint16_t rpc_par1 = msg.Get_UINT16();
	tb.Trigger_Select(rpc_par1);
	return true;
}

bool rpc__Trigger_Delay$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.Trigger_Delay(rpc_par1);
	return true;
}

bool rpc__Trigger_Timeout$vS(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint16_t rpc_par1 = msg.Get_UINT16();
	tb.Trigger_Timeout(rpc_par1);
	return true;
}

bool rpc__Trigger_SetGenPeriodic$vI(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(4)) return false;
	uint32_t rpc_par1 = msg.Get_UINT32();
	tb.Trigger_SetGenPeriodic(rpc_par1);
	return true;
}

bool rpc__Trigger_SetGenRandom$vI(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(4)) return false;
	uint32_t rpc_par1 = msg.Get_UINT32();
	tb.Trigger_SetGenRandom(rpc_par1);
	return true;
}

bool rpc__Trigger_Send$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.Trigger_Send(rpc_par1);
	return true;
}

bool rpc__Daq_Open$IIC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(5)) return false;
	uint32_t rpc_par1 = msg.Get_UINT32();
	uint8_t rpc_par2 = msg.Get_UINT8();
	uint32_t rpc_par0 = tb.Daq_Open(rpc_par1,rpc_par2);
	msg.CreateCmd(74);
	msg.Put_UINT32(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__Daq_Close$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.Daq_Close(rpc_par1);
	return true;
}

bool rpc__Daq_Start$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.Daq_Start(rpc_par1);
	return true;
}

bool rpc__Daq_Stop$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.Daq_Stop(rpc_par1);
	return true;
}

bool rpc__Daq_MemReset$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.Daq_MemReset(rpc_par1);
	return true;
}

bool rpc__Daq_GetSize$IC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint32_t rpc_par0 = tb.Daq_GetSize(rpc_par1);
	msg.CreateCmd(79);
	msg.Put_UINT32(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__Daq_FillLevel$CC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par0 = tb.Daq_FillLevel(rpc_par1);
	msg.CreateCmd(80);
	msg.Put_UINT8(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__Daq_FillLevel$C(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	uint8_t rpc_par0 = tb.Daq_FillLevel();
	msg.CreateCmd(81);
	msg.Put_UINT8(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__Daq_Read$C5SIC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(5)) return false;
	uint32_t rpc_par2 = msg.Get_UINT32();
	uint8_t rpc_par3 = msg.Get_UINT8();
	uint32_t rpc_par1_hdr;
	HWvectorR<uint16_t> rpc_par1;
	uint8_t rpc_par0 = tb.Daq_Read(rpc_par1,rpc_par2,rpc_par3);
	msg.CreateCmd(82);
	msg.Put_UINT8(rpc_par0);
	if (!msg.SendCmd()) return false;
	rpc_par1.Write(msg, rpc_par1_hdr);
	msg.Flush();
	return true;
}

bool rpc__Daq_Read$C5SI0IC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(9)) return false;
	uint32_t rpc_par2 = msg.Get_UINT32();
	uint32_t rpc_par3 = msg.Get_UINT32();
	uint8_t rpc_par4 = msg.Get_UINT8();
	uint32_t rpc_par1_hdr;
	HWvectorR<uint16_t> rpc_par1;
	uint8_t rpc_par0 = tb.Daq_Read(rpc_par1,rpc_par2,rpc_par3,rpc_par4);
	msg.CreateCmd(83);
	msg.Put_UINT8(rpc_par0);
	msg.Put_UINT32(rpc_par3);
	if (!msg.SendCmd()) return false;
	rpc_par1.Write(msg, rpc_par1_hdr);
	msg.Flush();
	return true;
}

bool rpc__Daq_Select_ADC$vSCCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(5)) return false;
	uint16_t rpc_par1 = msg.Get_UINT16();
	uint8_t rpc_par2 = msg.Get_UINT8();
	uint8_t rpc_par3 = msg.Get_UINT8();
	uint8_t rpc_par4 = msg.Get_UINT8();
	tb.Daq_Select_ADC(rpc_par1,rpc_par2,rpc_par3,rpc_par4);
	return true;
}

bool rpc__Daq_Select_Deser160$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.Daq_Select_Deser160(rpc_par1);
	return true;
}

bool rpc__Daq_Select_Deser400$v(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	tb.Daq_Select_Deser400();
	return true;
}

bool rpc__Daq_Deser400_Reset$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.Daq_Deser400_Reset(rpc_par1);
	return true;
}

bool rpc__Daq_Deser400_OldFormat$vb(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	bool rpc_par1 = msg.Get_BOOL();
	tb.Daq_Deser400_OldFormat(rpc_par1);
	return true;
}

bool rpc__Daq_Select_Datagenerator$vS(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint16_t rpc_par1 = msg.Get_UINT16();
	tb.Daq_Select_Datagenerator(rpc_par1);
	return true;
}

bool rpc__Daq_DeselectAll$v(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	tb.Daq_DeselectAll();
	return true;
}

bool rpc__Deser400_Enable$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.Deser400_Enable(rpc_par1);
	return true;
}

bool rpc__Deser400_Disable$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.Deser400_Disable(rpc_par1);
	return true;
}

bool rpc__Deser400_DisableAll$v(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	tb.Deser400_DisableAll();
	return true;
}

bool rpc__Deser400_SetPhase$vCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	tb.Deser400_SetPhase(rpc_par1,rpc_par2);
	return true;
}

bool rpc__Deser400_SetPhaseAuto$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.Deser400_SetPhaseAuto(rpc_par1);
	return true;
}

bool rpc__Deser400_SetPhaseAutoAll$v(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	tb.Deser400_SetPhaseAutoAll();
	return true;
}

bool rpc__Deser400_GetXor$CC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par0 = tb.Deser400_GetXor(rpc_par1);
	msg.CreateCmd(97);
	msg.Put_UINT8(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__Deser400_GetPhase$CC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par0 = tb.Deser400_GetPhase(rpc_par1);
	msg.CreateCmd(98);
	msg.Put_UINT8(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__Deser400_GateRun$vCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	tb.Deser400_GateRun(rpc_par1,rpc_par2);
	return true;
}

bool rpc__Deser400_GateSingle$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.Deser400_GateSingle(rpc_par1);
	return true;
}

bool rpc__Deser400_GateStop$v(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	tb.Deser400_GateStop();
	return true;
}

bool rpc__roc_I2cAddr$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.roc_I2cAddr(rpc_par1);
	return true;
}

bool rpc__roc_I2cAddr_Layer_1$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.roc_I2cAddr_Layer_1(rpc_par1);
	return true;
}

bool rpc__roc_ClrCal$v(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	tb.roc_ClrCal();
	return true;
}

bool rpc__roc_SetDAC$vCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	tb.roc_SetDAC(rpc_par1,rpc_par2);
	return true;
}

bool rpc__roc_Pix$vCCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(3)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	uint8_t rpc_par3 = msg.Get_UINT8();
	tb.roc_Pix(rpc_par1,rpc_par2,rpc_par3);
	return true;
}

bool rpc__roc_Pix_Trim$vCCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(3)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	uint8_t rpc_par3 = msg.Get_UINT8();
	tb.roc_Pix_Trim(rpc_par1,rpc_par2,rpc_par3);
	return true;
}

bool rpc__roc_Pix_Mask$vCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	tb.roc_Pix_Mask(rpc_par1,rpc_par2);
	return true;
}

bool rpc__roc_Pix_Cal$vCCb(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(3)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	bool rpc_par3 = msg.Get_BOOL();
	tb.roc_Pix_Cal(rpc_par1,rpc_par2,rpc_par3);
	return true;
}

bool rpc__roc_Col_Enable$vCb(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	bool rpc_par2 = msg.Get_BOOL();
	tb.roc_Col_Enable(rpc_par1,rpc_par2);
	return true;
}

bool rpc__roc_AllCol_Enable$vb(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	bool rpc_par1 = msg.Get_BOOL();
	tb.roc_AllCol_Enable(rpc_par1);
	return true;
}

bool rpc__roc_Col_Mask$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.roc_Col_Mask(rpc_par1);
	return true;
}

bool rpc__roc_Chip_Mask$v(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	tb.roc_Chip_Mask();
	return true;
}

bool rpc__TBM_Present$b(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	bool rpc_par0 = tb.TBM_Present();
	msg.CreateCmd(114);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__tbm_Enable$vb(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	bool rpc_par1 = msg.Get_BOOL();
	tb.tbm_Enable(rpc_par1);
	return true;
}

bool rpc__tbm_Addr$vCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	tb.tbm_Addr(rpc_par1,rpc_par2);
	return true;
}

bool rpc__mod_Addr$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.mod_Addr(rpc_par1);
	return true;
}

bool rpc__mod_Addr$vCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	tb.mod_Addr(rpc_par1,rpc_par2);
	return true;
}

bool rpc__tbm_Set$vCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	tb.tbm_Set(rpc_par1,rpc_par2);
	return true;
}

bool rpc__tbm_SelectRDA$vC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	tb.tbm_SelectRDA(rpc_par1);
	return true;
}

bool rpc__tbm_Get$bC0C(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	bool rpc_par0 = tb.tbm_Get(rpc_par1,rpc_par2);
	msg.CreateCmd(121);
	msg.Put_BOOL(rpc_par0);
	msg.Put_UINT8(rpc_par2);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__tbm_GetRaw$bC0I(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(5)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint32_t rpc_par2 = msg.Get_UINT32();
	bool rpc_par0 = tb.tbm_GetRaw(rpc_par1,rpc_par2);
	msg.CreateCmd(122);
	msg.Put_BOOL(rpc_par0);
	msg.Put_UINT32(rpc_par2);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__TrimChip$s1s(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	vector<int16_t> rpc_par1; if (!rpc_RecvVector(msg, rpc_par1)) return false;
	int16_t rpc_par0 = tb.TrimChip(rpc_par1);
	msg.CreateCmd(123);
	msg.Put_INT16(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__TestColPixel$bCCb2C(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(3)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	bool rpc_par3 = msg.Get_BOOL();
	uint32_t rpc_par4_hdr;
	vectorR<uint8_t> rpc_par4;
	bool rpc_par0 = tb.TestColPixel(rpc_par1,rpc_par2,rpc_par3,rpc_par4);
	msg.CreateCmd(124);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	if (!rpc_SendVector(msg, rpc_par4_hdr, rpc_par4)) return false;
	msg.Flush();
	return true;
}

bool rpc__Ethernet_Send$v3c(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	string rpc_par1; if (!msg.RecvString(rpc_par1)) return false;
	tb.Ethernet_Send(rpc_par1);
	return true;
}

bool rpc__Ethernet_RecvPackets$I(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	uint32_t rpc_par0 = tb.Ethernet_RecvPackets();
	msg.CreateCmd(126);
	msg.Put_UINT32(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__LoopInterruptReset$v(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	tb.LoopInterruptReset();
	return true;
}

bool rpc__SetLoopTriggerDelay$vS(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint16_t rpc_par1 = msg.Get_UINT16();
	tb.SetLoopTriggerDelay(rpc_par1);
	return true;
}

bool rpc__SetLoopTrimDelay$vS(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(2)) return false;
	uint16_t rpc_par1 = msg.Get_UINT16();
	tb.SetLoopTrimDelay(rpc_par1);
	return true;
}

bool rpc__SetI2CAddresses$b1C(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	vector<uint8_t> rpc_par1; if (!rpc_RecvVector(msg, rpc_par1)) return false;
	bool rpc_par0 = tb.SetI2CAddresses(rpc_par1);
	msg.CreateCmd(130);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__SetTrimValues$bC1C(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	vector<uint8_t> rpc_par2; if (!rpc_RecvVector(msg, rpc_par2)) return false;
	bool rpc_par0 = tb.SetTrimValues(rpc_par1,rpc_par2);
	msg.CreateCmd(131);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__LoopMultiRocAllPixelsCalibrate$b1CSS(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(4)) return false;
	uint16_t rpc_par2 = msg.Get_UINT16();
	uint16_t rpc_par3 = msg.Get_UINT16();
	vector<uint8_t> rpc_par1; if (!rpc_RecvVector(msg, rpc_par1)) return false;
	bool rpc_par0 = tb.LoopMultiRocAllPixelsCalibrate(rpc_par1,rpc_par2,rpc_par3);
	msg.CreateCmd(132);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__LoopMultiRocOnePixelCalibrate$b1CCCSS(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(6)) return false;
	uint8_t rpc_par2 = msg.Get_UINT8();
	uint8_t rpc_par3 = msg.Get_UINT8();
	uint16_t rpc_par4 = msg.Get_UINT16();
	uint16_t rpc_par5 = msg.Get_UINT16();
	vector<uint8_t> rpc_par1; if (!rpc_RecvVector(msg, rpc_par1)) return false;
	bool rpc_par0 = tb.LoopMultiRocOnePixelCalibrate(rpc_par1,rpc_par2,rpc_par3,rpc_par4,rpc_par5);
	msg.CreateCmd(133);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__LoopSingleRocAllPixelsCalibrate$bCSS(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(5)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint16_t rpc_par2 = msg.Get_UINT16();
	uint16_t rpc_par3 = msg.Get_UINT16();
	bool rpc_par0 = tb.LoopSingleRocAllPixelsCalibrate(rpc_par1,rpc_par2,rpc_par3);
	msg.CreateCmd(134);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__LoopSingleRocOnePixelCalibrate$bCCCSS(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(7)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	uint8_t rpc_par3 = msg.Get_UINT8();
	uint16_t rpc_par4 = msg.Get_UINT16();
	uint16_t rpc_par5 = msg.Get_UINT16();
	bool rpc_par0 = tb.LoopSingleRocOnePixelCalibrate(rpc_par1,rpc_par2,rpc_par3,rpc_par4,rpc_par5);
	msg.CreateCmd(135);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__LoopMultiRocAllPixelsDacScan$b1CSSCCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(7)) return false;
	uint16_t rpc_par2 = msg.Get_UINT16();
	uint16_t rpc_par3 = msg.Get_UINT16();
	uint8_t rpc_par4 = msg.Get_UINT8();
	uint8_t rpc_par5 = msg.Get_UINT8();
	uint8_t rpc_par6 = msg.Get_UINT8();
	vector<uint8_t> rpc_par1; if (!rpc_RecvVector(msg, rpc_par1)) return false;
	bool rpc_par0 = tb.LoopMultiRocAllPixelsDacScan(rpc_par1,rpc_par2,rpc_par3,rpc_par4,rpc_par5,rpc_par6);
	msg.CreateCmd(136);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__LoopMultiRocAllPixelsDacScan$b1CSSCCCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(8)) return false;
	uint16_t rpc_par2 = msg.Get_UINT16();
	uint16_t rpc_par3 = msg.Get_UINT16();
	uint8_t rpc_par4 = msg.Get_UINT8();
	uint8_t rpc_par5 = msg.Get_UINT8();
	uint8_t rpc_par6 = msg.Get_UINT8();
	uint8_t rpc_par7 = msg.Get_UINT8();
	vector<uint8_t> rpc_par1; if (!rpc_RecvVector(msg, rpc_par1)) return false;
	bool rpc_par0 = tb.LoopMultiRocAllPixelsDacScan(rpc_par1,rpc_par2,rpc_par3,rpc_par4,rpc_par5,rpc_par6,rpc_par7);
	msg.CreateCmd(137);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__LoopMultiRocOnePixelDacScan$b1CCCSSCCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(9)) return false;
	uint8_t rpc_par2 = msg.Get_UINT8();
	uint8_t rpc_par3 = msg.Get_UINT8();
	uint16_t rpc_par4 = msg.Get_UINT16();
	uint16_t rpc_par5 = msg.Get_UINT16();
	uint8_t rpc_par6 = msg.Get_UINT8();
	uint8_t rpc_par7 = msg.Get_UINT8();
	uint8_t rpc_par8 = msg.Get_UINT8();
	vector<uint8_t> rpc_par1; if (!rpc_RecvVector(msg, rpc_par1)) return false;
	bool rpc_par0 = tb.LoopMultiRocOnePixelDacScan(rpc_par1,rpc_par2,rpc_par3,rpc_par4,rpc_par5,rpc_par6,rpc_par7,rpc_par8);
	msg.CreateCmd(138);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__LoopMultiRocOnePixelDacScan$b1CCCSSCCCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(10)) return false;
	uint8_t rpc_par2 = msg.Get_UINT8();
	uint8_t rpc_par3 = msg.Get_UINT8();
	uint16_t rpc_par4 = msg.Get_UINT16();
	uint16_t rpc_par5 = msg.Get_UINT16();
	uint8_t rpc_par6 = msg.Get_UINT8();
	uint8_t rpc_par7 = msg.Get_UINT8();
	uint8_t rpc_par8 = msg.Get_UINT8();
	uint8_t rpc_par9 = msg.Get_UINT8();
	vector<uint8_t> rpc_par1; if (!rpc_RecvVector(msg, rpc_par1)) return false;
	bool rpc_par0 = tb.LoopMultiRocOnePixelDacScan(rpc_par1,rpc_par2,rpc_par3,rpc_par4,rpc_par5,rpc_par6,rpc_par7,rpc_par8,rpc_par9);
	msg.CreateCmd(139);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__LoopSingleRocAllPixelsDacScan$bCSSCCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(8)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint16_t rpc_par2 = msg.Get_UINT16();
	uint16_t rpc_par3 = msg.Get_UINT16();
	uint8_t rpc_par4 = msg.Get_UINT8();
	uint8_t rpc_par5 = msg.Get_UINT8();
	uint8_t rpc_par6 = msg.Get_UINT8();
	bool rpc_par0 = tb.LoopSingleRocAllPixelsDacScan(rpc_par1,rpc_par2,rpc_par3,rpc_par4,rpc_par5,rpc_par6);
	msg.CreateCmd(140);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__LoopSingleRocAllPixelsDacScan$bCSSCCCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(9)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint16_t rpc_par2 = msg.Get_UINT16();
	uint16_t rpc_par3 = msg.Get_UINT16();
	uint8_t rpc_par4 = msg.Get_UINT8();
	uint8_t rpc_par5 = msg.Get_UINT8();
	uint8_t rpc_par6 = msg.Get_UINT8();
	uint8_t rpc_par7 = msg.Get_UINT8();
	bool rpc_par0 = tb.LoopSingleRocAllPixelsDacScan(rpc_par1,rpc_par2,rpc_par3,rpc_par4,rpc_par5,rpc_par6,rpc_par7);
	msg.CreateCmd(141);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__LoopSingleRocOnePixelDacScan$bCCCSSCCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(10)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	uint8_t rpc_par3 = msg.Get_UINT8();
	uint16_t rpc_par4 = msg.Get_UINT16();
	uint16_t rpc_par5 = msg.Get_UINT16();
	uint8_t rpc_par6 = msg.Get_UINT8();
	uint8_t rpc_par7 = msg.Get_UINT8();
	uint8_t rpc_par8 = msg.Get_UINT8();
	bool rpc_par0 = tb.LoopSingleRocOnePixelDacScan(rpc_par1,rpc_par2,rpc_par3,rpc_par4,rpc_par5,rpc_par6,rpc_par7,rpc_par8);
	msg.CreateCmd(142);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__LoopSingleRocOnePixelDacScan$bCCCSSCCCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(11)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	uint8_t rpc_par3 = msg.Get_UINT8();
	uint16_t rpc_par4 = msg.Get_UINT16();
	uint16_t rpc_par5 = msg.Get_UINT16();
	uint8_t rpc_par6 = msg.Get_UINT8();
	uint8_t rpc_par7 = msg.Get_UINT8();
	uint8_t rpc_par8 = msg.Get_UINT8();
	uint8_t rpc_par9 = msg.Get_UINT8();
	bool rpc_par0 = tb.LoopSingleRocOnePixelDacScan(rpc_par1,rpc_par2,rpc_par3,rpc_par4,rpc_par5,rpc_par6,rpc_par7,rpc_par8,rpc_par9);
	msg.CreateCmd(143);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__LoopMultiRocAllPixelsDacDacScan$b1CSSCCCCCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(10)) return false;
	uint16_t rpc_par2 = msg.Get_UINT16();
	uint16_t rpc_par3 = msg.Get_UINT16();
	uint8_t rpc_par4 = msg.Get_UINT8();
	uint8_t rpc_par5 = msg.Get_UINT8();
	uint8_t rpc_par6 = msg.Get_UINT8();
	uint8_t rpc_par7 = msg.Get_UINT8();
	uint8_t rpc_par8 = msg.Get_UINT8();
	uint8_t rpc_par9 = msg.Get_UINT8();
	vector<uint8_t> rpc_par1; if (!rpc_RecvVector(msg, rpc_par1)) return false;
	bool rpc_par0 = tb.LoopMultiRocAllPixelsDacDacScan(rpc_par1,rpc_par2,rpc_par3,rpc_par4,rpc_par5,rpc_par6,rpc_par7,rpc_par8,rpc_par9);
	msg.CreateCmd(144);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__LoopMultiRocAllPixelsDacDacScan$b1CSSCCCCCCCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(12)) return false;
	uint16_t rpc_par2 = msg.Get_UINT16();
	uint16_t rpc_par3 = msg.Get_UINT16();
	uint8_t rpc_par4 = msg.Get_UINT8();
	uint8_t rpc_par5 = msg.Get_UINT8();
	uint8_t rpc_par6 = msg.Get_UINT8();
	uint8_t rpc_par7 = msg.Get_UINT8();
	uint8_t rpc_par8 = msg.Get_UINT8();
	uint8_t rpc_par9 = msg.Get_UINT8();
	uint8_t rpc_par10 = msg.Get_UINT8();
	uint8_t rpc_par11 = msg.Get_UINT8();
	vector<uint8_t> rpc_par1; if (!rpc_RecvVector(msg, rpc_par1)) return false;
	bool rpc_par0 = tb.LoopMultiRocAllPixelsDacDacScan(rpc_par1,rpc_par2,rpc_par3,rpc_par4,rpc_par5,rpc_par6,rpc_par7,rpc_par8,rpc_par9,rpc_par10,rpc_par11);
	msg.CreateCmd(145);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__LoopMultiRocOnePixelDacDacScan$b1CCCSSCCCCCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(12)) return false;
	uint8_t rpc_par2 = msg.Get_UINT8();
	uint8_t rpc_par3 = msg.Get_UINT8();
	uint16_t rpc_par4 = msg.Get_UINT16();
	uint16_t rpc_par5 = msg.Get_UINT16();
	uint8_t rpc_par6 = msg.Get_UINT8();
	uint8_t rpc_par7 = msg.Get_UINT8();
	uint8_t rpc_par8 = msg.Get_UINT8();
	uint8_t rpc_par9 = msg.Get_UINT8();
	uint8_t rpc_par10 = msg.Get_UINT8();
	uint8_t rpc_par11 = msg.Get_UINT8();
	vector<uint8_t> rpc_par1; if (!rpc_RecvVector(msg, rpc_par1)) return false;
	bool rpc_par0 = tb.LoopMultiRocOnePixelDacDacScan(rpc_par1,rpc_par2,rpc_par3,rpc_par4,rpc_par5,rpc_par6,rpc_par7,rpc_par8,rpc_par9,rpc_par10,rpc_par11);
	msg.CreateCmd(146);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__LoopMultiRocOnePixelDacDacScan$b1CCCSSCCCCCCCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(14)) return false;
	uint8_t rpc_par2 = msg.Get_UINT8();
	uint8_t rpc_par3 = msg.Get_UINT8();
	uint16_t rpc_par4 = msg.Get_UINT16();
	uint16_t rpc_par5 = msg.Get_UINT16();
	uint8_t rpc_par6 = msg.Get_UINT8();
	uint8_t rpc_par7 = msg.Get_UINT8();
	uint8_t rpc_par8 = msg.Get_UINT8();
	uint8_t rpc_par9 = msg.Get_UINT8();
	uint8_t rpc_par10 = msg.Get_UINT8();
	uint8_t rpc_par11 = msg.Get_UINT8();
	uint8_t rpc_par12 = msg.Get_UINT8();
	uint8_t rpc_par13 = msg.Get_UINT8();
	vector<uint8_t> rpc_par1; if (!rpc_RecvVector(msg, rpc_par1)) return false;
	bool rpc_par0 = tb.LoopMultiRocOnePixelDacDacScan(rpc_par1,rpc_par2,rpc_par3,rpc_par4,rpc_par5,rpc_par6,rpc_par7,rpc_par8,rpc_par9,rpc_par10,rpc_par11,rpc_par12,rpc_par13);
	msg.CreateCmd(147);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__LoopSingleRocAllPixelsDacDacScan$bCSSCCCCCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(11)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint16_t rpc_par2 = msg.Get_UINT16();
	uint16_t rpc_par3 = msg.Get_UINT16();
	uint8_t rpc_par4 = msg.Get_UINT8();
	uint8_t rpc_par5 = msg.Get_UINT8();
	uint8_t rpc_par6 = msg.Get_UINT8();
	uint8_t rpc_par7 = msg.Get_UINT8();
	uint8_t rpc_par8 = msg.Get_UINT8();
	uint8_t rpc_par9 = msg.Get_UINT8();
	bool rpc_par0 = tb.LoopSingleRocAllPixelsDacDacScan(rpc_par1,rpc_par2,rpc_par3,rpc_par4,rpc_par5,rpc_par6,rpc_par7,rpc_par8,rpc_par9);
	msg.CreateCmd(148);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__LoopSingleRocAllPixelsDacDacScan$bCSSCCCCCCCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(13)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint16_t rpc_par2 = msg.Get_UINT16();
	uint16_t rpc_par3 = msg.Get_UINT16();
	uint8_t rpc_par4 = msg.Get_UINT8();
	uint8_t rpc_par5 = msg.Get_UINT8();
	uint8_t rpc_par6 = msg.Get_UINT8();
	uint8_t rpc_par7 = msg.Get_UINT8();
	uint8_t rpc_par8 = msg.Get_UINT8();
	uint8_t rpc_par9 = msg.Get_UINT8();
	uint8_t rpc_par10 = msg.Get_UINT8();
	uint8_t rpc_par11 = msg.Get_UINT8();
	bool rpc_par0 = tb.LoopSingleRocAllPixelsDacDacScan(rpc_par1,rpc_par2,rpc_par3,rpc_par4,rpc_par5,rpc_par6,rpc_par7,rpc_par8,rpc_par9,rpc_par10,rpc_par11);
	msg.CreateCmd(149);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__LoopSingleRocOnePixelDacDacScan$bCCCSSCCCCCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(13)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	uint8_t rpc_par3 = msg.Get_UINT8();
	uint16_t rpc_par4 = msg.Get_UINT16();
	uint16_t rpc_par5 = msg.Get_UINT16();
	uint8_t rpc_par6 = msg.Get_UINT8();
	uint8_t rpc_par7 = msg.Get_UINT8();
	uint8_t rpc_par8 = msg.Get_UINT8();
	uint8_t rpc_par9 = msg.Get_UINT8();
	uint8_t rpc_par10 = msg.Get_UINT8();
	uint8_t rpc_par11 = msg.Get_UINT8();
	bool rpc_par0 = tb.LoopSingleRocOnePixelDacDacScan(rpc_par1,rpc_par2,rpc_par3,rpc_par4,rpc_par5,rpc_par6,rpc_par7,rpc_par8,rpc_par9,rpc_par10,rpc_par11);
	msg.CreateCmd(150);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__LoopSingleRocOnePixelDacDacScan$bCCCSSCCCCCCCC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(15)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint8_t rpc_par2 = msg.Get_UINT8();
	uint8_t rpc_par3 = msg.Get_UINT8();
	uint16_t rpc_par4 = msg.Get_UINT16();
	uint16_t rpc_par5 = msg.Get_UINT16();
	uint8_t rpc_par6 = msg.Get_UINT8();
	uint8_t rpc_par7 = msg.Get_UINT8();
	uint8_t rpc_par8 = msg.Get_UINT8();
	uint8_t rpc_par9 = msg.Get_UINT8();
	uint8_t rpc_par10 = msg.Get_UINT8();
	uint8_t rpc_par11 = msg.Get_UINT8();
	uint8_t rpc_par12 = msg.Get_UINT8();
	uint8_t rpc_par13 = msg.Get_UINT8();
	bool rpc_par0 = tb.LoopSingleRocOnePixelDacDacScan(rpc_par1,rpc_par2,rpc_par3,rpc_par4,rpc_par5,rpc_par6,rpc_par7,rpc_par8,rpc_par9,rpc_par10,rpc_par11,rpc_par12,rpc_par13);
	msg.CreateCmd(151);
	msg.Put_BOOL(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

bool rpc__VectorTest$v1S2S(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(0)) return false;
	vector<uint16_t> rpc_par1; if (!rpc_RecvVector(msg, rpc_par1)) return false;
	uint32_t rpc_par2_hdr;
	vectorR<uint16_t> rpc_par2;
	tb.VectorTest(rpc_par1,rpc_par2);
	msg.CreateCmd(152);
	if (!msg.SendCmd()) return false;
	if (!rpc_SendVector(msg, rpc_par2_hdr, rpc_par2)) return false;
	msg.Flush();
	return true;
}

bool rpc__GetADC$SC(rpcMessage &msg)
{
	if (!msg.CheckCmdSize(1)) return false;
	uint8_t rpc_par1 = msg.Get_UINT8();
	uint16_t rpc_par0 = tb.GetADC(rpc_par1);
	msg.CreateCmd(153);
	msg.Put_UINT16(rpc_par0);
	if (!msg.SendCmd()) return false;
	msg.Flush();
	return true;
}

const uint16_t rpc_cmdListSize = 154;

const CRpcCall rpc_cmdlist[] =
{
	/*     0 */ { rpc__GetRpcVersion$S, "GetRpcVersion$S" },
	/*     1 */ { rpc__GetRpcCallId$i3c, "GetRpcCallId$i3c" },
	/*     2 */ { rpc__GetRpcTimestamp$v4c, "GetRpcTimestamp$v4c" },
	/*     3 */ { rpc__GetRpcCallCount$i, "GetRpcCallCount$i" },
	/*     4 */ { rpc__GetRpcCallName$bi4c, "GetRpcCallName$bi4c" },
	/*     5 */ { rpc__GetRpcCallHash$I, "GetRpcCallHash$I" },
	/*     6 */ { rpc__GetInfo$v4c, "GetInfo$v4c" },
	/*     7 */ { rpc__GetBoardId$S, "GetBoardId$S" },
	/*     8 */ { rpc__GetHWVersion$v4c, "GetHWVersion$v4c" },
	/*     9 */ { rpc__GetFWVersion$S, "GetFWVersion$S" },
	/*    10 */ { rpc__GetSWVersion$S, "GetSWVersion$S" },
	/*    11 */ { rpc__UpgradeGetVersion$S, "UpgradeGetVersion$S" },
	/*    12 */ { rpc__UpgradeStart$CS, "UpgradeStart$CS" },
	/*    13 */ { rpc__UpgradeData$C3c, "UpgradeData$C3c" },
	/*    14 */ { rpc__UpgradeError$C, "UpgradeError$C" },
	/*    15 */ { rpc__UpgradeErrorMsg$v4c, "UpgradeErrorMsg$v4c" },
	/*    16 */ { rpc__UpgradeExec$vS, "UpgradeExec$vS" },
	/*    17 */ { rpc__Init$v, "Init$v" },
	/*    18 */ { rpc__Welcome$v, "Welcome$v" },
	/*    19 */ { rpc__SetLed$vC, "SetLed$vC" },
	/*    20 */ { rpc__cDelay$vS, "cDelay$vS" },
	/*    21 */ { rpc__uDelay$vS, "uDelay$vS" },
	/*    22 */ { rpc__SetClockSource$vC, "SetClockSource$vC" },
	/*    23 */ { rpc__IsClockPresent$b, "IsClockPresent$b" },
	/*    24 */ { rpc__SetClock$vC, "SetClock$vC" },
	/*    25 */ { rpc__SetClockStretch$vCSS, "SetClockStretch$vCSS" },
	/*    26 */ { rpc__Sig_SetMode$vCC, "Sig_SetMode$vCC" },
	/*    27 */ { rpc__Sig_SetPRBS$vCC, "Sig_SetPRBS$vCC" },
	/*    28 */ { rpc__Sig_SetDelay$vCSc, "Sig_SetDelay$vCSc" },
	/*    29 */ { rpc__Sig_SetLevel$vCC, "Sig_SetLevel$vCC" },
	/*    30 */ { rpc__Sig_SetOffset$vC, "Sig_SetOffset$vC" },
	/*    31 */ { rpc__Sig_SetLVDS$v, "Sig_SetLVDS$v" },
	/*    32 */ { rpc__Sig_SetLCDS$v, "Sig_SetLCDS$v" },
	/*    33 */ { rpc__Sig_SetRdaToutDelay$vC, "Sig_SetRdaToutDelay$vC" },
	/*    34 */ { rpc__SignalProbeD1$vC, "SignalProbeD1$vC" },
	/*    35 */ { rpc__SignalProbeD2$vC, "SignalProbeD2$vC" },
	/*    36 */ { rpc__SignalProbeDeserD1$vCC, "SignalProbeDeserD1$vCC" },
	/*    37 */ { rpc__SignalProbeDeserD2$vCC, "SignalProbeDeserD2$vCC" },
	/*    38 */ { rpc__SignalProbeA1$vC, "SignalProbeA1$vC" },
	/*    39 */ { rpc__SignalProbeA2$vC, "SignalProbeA2$vC" },
	/*    40 */ { rpc__SignalProbeADC$vCC, "SignalProbeADC$vCC" },
	/*    41 */ { rpc__Pon$v, "Pon$v" },
	/*    42 */ { rpc__Poff$v, "Poff$v" },
	/*    43 */ { rpc___SetVD$vS, "_SetVD$vS" },
	/*    44 */ { rpc___SetVA$vS, "_SetVA$vS" },
	/*    45 */ { rpc___SetID$vS, "_SetID$vS" },
	/*    46 */ { rpc___SetIA$vS, "_SetIA$vS" },
	/*    47 */ { rpc___GetVD$S, "_GetVD$S" },
	/*    48 */ { rpc___GetVA$S, "_GetVA$S" },
	/*    49 */ { rpc___GetID$S, "_GetID$S" },
	/*    50 */ { rpc___GetIA$S, "_GetIA$S" },
	/*    51 */ { rpc___GetVD_Reg$S, "_GetVD_Reg$S" },
	/*    52 */ { rpc___GetVDAC_Reg$S, "_GetVDAC_Reg$S" },
	/*    53 */ { rpc___GetVD_Cap$S, "_GetVD_Cap$S" },
	/*    54 */ { rpc__HVon$v, "HVon$v" },
	/*    55 */ { rpc__HVoff$v, "HVoff$v" },
	/*    56 */ { rpc__ResetOn$v, "ResetOn$v" },
	/*    57 */ { rpc__ResetOff$v, "ResetOff$v" },
	/*    58 */ { rpc__GetStatus$C, "GetStatus$C" },
	/*    59 */ { rpc__SetRocAddress$vC, "SetRocAddress$vC" },
	/*    60 */ { rpc__Pg_SetCmd$vSS, "Pg_SetCmd$vSS" },
	/*    61 */ { rpc__Pg_SetCmdAll$v1S, "Pg_SetCmdAll$v1S" },
	/*    62 */ { rpc__Pg_SetSum$vS, "Pg_SetSum$vS" },
	/*    63 */ { rpc__Pg_Stop$v, "Pg_Stop$v" },
	/*    64 */ { rpc__Pg_Single$v, "Pg_Single$v" },
	/*    65 */ { rpc__Pg_Trigger$v, "Pg_Trigger$v" },
	/*    66 */ { rpc__Pg_Triggers$vIS, "Pg_Triggers$vIS" },
	/*    67 */ { rpc__Pg_Loop$vS, "Pg_Loop$vS" },
	/*    68 */ { rpc__Trigger_Select$vS, "Trigger_Select$vS" },
	/*    69 */ { rpc__Trigger_Delay$vC, "Trigger_Delay$vC" },
	/*    70 */ { rpc__Trigger_Timeout$vS, "Trigger_Timeout$vS" },
	/*    71 */ { rpc__Trigger_SetGenPeriodic$vI, "Trigger_SetGenPeriodic$vI" },
	/*    72 */ { rpc__Trigger_SetGenRandom$vI, "Trigger_SetGenRandom$vI" },
	/*    73 */ { rpc__Trigger_Send$vC, "Trigger_Send$vC" },
	/*    74 */ { rpc__Daq_Open$IIC, "Daq_Open$IIC" },
	/*    75 */ { rpc__Daq_Close$vC, "Daq_Close$vC" },
	/*    76 */ { rpc__Daq_Start$vC, "Daq_Start$vC" },
	/*    77 */ { rpc__Daq_Stop$vC, "Daq_Stop$vC" },
	/*    78 */ { rpc__Daq_MemReset$vC, "Daq_MemReset$vC" },
	/*    79 */ { rpc__Daq_GetSize$IC, "Daq_GetSize$IC" },
	/*    80 */ { rpc__Daq_FillLevel$CC, "Daq_FillLevel$CC" },
	/*    81 */ { rpc__Daq_FillLevel$C, "Daq_FillLevel$C" },
	/*    82 */ { rpc__Daq_Read$C5SIC, "Daq_Read$C5SIC" },
	/*    83 */ { rpc__Daq_Read$C5SI0IC, "Daq_Read$C5SI0IC" },
	/*    84 */ { rpc__Daq_Select_ADC$vSCCC, "Daq_Select_ADC$vSCCC" },
	/*    85 */ { rpc__Daq_Select_Deser160$vC, "Daq_Select_Deser160$vC" },
	/*    86 */ { rpc__Daq_Select_Deser400$v, "Daq_Select_Deser400$v" },
	/*    87 */ { rpc__Daq_Deser400_Reset$vC, "Daq_Deser400_Reset$vC" },
	/*    88 */ { rpc__Daq_Deser400_OldFormat$vb, "Daq_Deser400_OldFormat$vb" },
	/*    89 */ { rpc__Daq_Select_Datagenerator$vS, "Daq_Select_Datagenerator$vS" },
	/*    90 */ { rpc__Daq_DeselectAll$v, "Daq_DeselectAll$v" },
	/*    91 */ { rpc__Deser400_Enable$vC, "Deser400_Enable$vC" },
	/*    92 */ { rpc__Deser400_Disable$vC, "Deser400_Disable$vC" },
	/*    93 */ { rpc__Deser400_DisableAll$v, "Deser400_DisableAll$v" },
	/*    94 */ { rpc__Deser400_SetPhase$vCC, "Deser400_SetPhase$vCC" },
	/*    95 */ { rpc__Deser400_SetPhaseAuto$vC, "Deser400_SetPhaseAuto$vC" },
	/*    96 */ { rpc__Deser400_SetPhaseAutoAll$v, "Deser400_SetPhaseAutoAll$v" },
	/*    97 */ { rpc__Deser400_GetXor$CC, "Deser400_GetXor$CC" },
	/*    98 */ { rpc__Deser400_GetPhase$CC, "Deser400_GetPhase$CC" },
	/*    99 */ { rpc__Deser400_GateRun$vCC, "Deser400_GateRun$vCC" },
	/*   100 */ { rpc__Deser400_GateSingle$vC, "Deser400_GateSingle$vC" },
	/*   101 */ { rpc__Deser400_GateStop$v, "Deser400_GateStop$v" },
	/*   102 */ { rpc__roc_I2cAddr$vC, "roc_I2cAddr$vC" },
	/*   103 */ { rpc__roc_I2cAddr_Layer_1$vC, "roc_I2cAddr_Layer_1$vC" },
	/*   104 */ { rpc__roc_ClrCal$v, "roc_ClrCal$v" },
	/*   105 */ { rpc__roc_SetDAC$vCC, "roc_SetDAC$vCC" },
	/*   106 */ { rpc__roc_Pix$vCCC, "roc_Pix$vCCC" },
	/*   107 */ { rpc__roc_Pix_Trim$vCCC, "roc_Pix_Trim$vCCC" },
	/*   108 */ { rpc__roc_Pix_Mask$vCC, "roc_Pix_Mask$vCC" },
	/*   109 */ { rpc__roc_Pix_Cal$vCCb, "roc_Pix_Cal$vCCb" },
	/*   110 */ { rpc__roc_Col_Enable$vCb, "roc_Col_Enable$vCb" },
	/*   111 */ { rpc__roc_AllCol_Enable$vb, "roc_AllCol_Enable$vb" },
	/*   112 */ { rpc__roc_Col_Mask$vC, "roc_Col_Mask$vC" },
	/*   113 */ { rpc__roc_Chip_Mask$v, "roc_Chip_Mask$v" },
	/*   114 */ { rpc__TBM_Present$b, "TBM_Present$b" },
	/*   115 */ { rpc__tbm_Enable$vb, "tbm_Enable$vb" },
	/*   116 */ { rpc__tbm_Addr$vCC, "tbm_Addr$vCC" },
	/*   117 */ { rpc__mod_Addr$vC, "mod_Addr$vC" },
	/*   118 */ { rpc__mod_Addr$vCC, "mod_Addr$vCC" },
	/*   119 */ { rpc__tbm_Set$vCC, "tbm_Set$vCC" },
	/*   120 */ { rpc__tbm_SelectRDA$vC, "tbm_SelectRDA$vC" },
	/*   121 */ { rpc__tbm_Get$bC0C, "tbm_Get$bC0C" },
	/*   122 */ { rpc__tbm_GetRaw$bC0I, "tbm_GetRaw$bC0I" },
	/*   123 */ { rpc__TrimChip$s1s, "TrimChip$s1s" },
	/*   124 */ { rpc__TestColPixel$bCCb2C, "TestColPixel$bCCb2C" },
	/*   125 */ { rpc__Ethernet_Send$v3c, "Ethernet_Send$v3c" },
	/*   126 */ { rpc__Ethernet_RecvPackets$I, "Ethernet_RecvPackets$I" },
	/*   127 */ { rpc__LoopInterruptReset$v, "LoopInterruptReset$v" },
	/*   128 */ { rpc__SetLoopTriggerDelay$vS, "SetLoopTriggerDelay$vS" },
	/*   129 */ { rpc__SetLoopTrimDelay$vS, "SetLoopTrimDelay$vS" },
	/*   130 */ { rpc__SetI2CAddresses$b1C, "SetI2CAddresses$b1C" },
	/*   131 */ { rpc__SetTrimValues$bC1C, "SetTrimValues$bC1C" },
	/*   132 */ { rpc__LoopMultiRocAllPixelsCalibrate$b1CSS, "LoopMultiRocAllPixelsCalibrate$b1CSS" },
	/*   133 */ { rpc__LoopMultiRocOnePixelCalibrate$b1CCCSS, "LoopMultiRocOnePixelCalibrate$b1CCCSS" },
	/*   134 */ { rpc__LoopSingleRocAllPixelsCalibrate$bCSS, "LoopSingleRocAllPixelsCalibrate$bCSS" },
	/*   135 */ { rpc__LoopSingleRocOnePixelCalibrate$bCCCSS, "LoopSingleRocOnePixelCalibrate$bCCCSS" },
	/*   136 */ { rpc__LoopMultiRocAllPixelsDacScan$b1CSSCCC, "LoopMultiRocAllPixelsDacScan$b1CSSCCC" },
	/*   137 */ { rpc__LoopMultiRocAllPixelsDacScan$b1CSSCCCC, "LoopMultiRocAllPixelsDacScan$b1CSSCCCC" },
	/*   138 */ { rpc__LoopMultiRocOnePixelDacScan$b1CCCSSCCC, "LoopMultiRocOnePixelDacScan$b1CCCSSCCC" },
	/*   139 */ { rpc__LoopMultiRocOnePixelDacScan$b1CCCSSCCCC, "LoopMultiRocOnePixelDacScan$b1CCCSSCCCC" },
	/*   140 */ { rpc__LoopSingleRocAllPixelsDacScan$bCSSCCC, "LoopSingleRocAllPixelsDacScan$bCSSCCC" },
	/*   141 */ { rpc__LoopSingleRocAllPixelsDacScan$bCSSCCCC, "LoopSingleRocAllPixelsDacScan$bCSSCCCC" },
	/*   142 */ { rpc__LoopSingleRocOnePixelDacScan$bCCCSSCCC, "LoopSingleRocOnePixelDacScan$bCCCSSCCC" },
	/*   143 */ { rpc__LoopSingleRocOnePixelDacScan$bCCCSSCCCC, "LoopSingleRocOnePixelDacScan$bCCCSSCCCC" },
	/*   144 */ { rpc__LoopMultiRocAllPixelsDacDacScan$b1CSSCCCCCC, "LoopMultiRocAllPixelsDacDacScan$b1CSSCCCCCC" },
	/*   145 */ { rpc__LoopMultiRocAllPixelsDacDacScan$b1CSSCCCCCCCC, "LoopMultiRocAllPixelsDacDacScan$b1CSSCCCCCCCC" },
	/*   146 */ { rpc__LoopMultiRocOnePixelDacDacScan$b1CCCSSCCCCCC, "LoopMultiRocOnePixelDacDacScan$b1CCCSSCCCCCC" },
	/*   147 */ { rpc__LoopMultiRocOnePixelDacDacScan$b1CCCSSCCCCCCCC, "LoopMultiRocOnePixelDacDacScan$b1CCCSSCCCCCCCC" },
	/*   148 */ { rpc__LoopSingleRocAllPixelsDacDacScan$bCSSCCCCCC, "LoopSingleRocAllPixelsDacDacScan$bCSSCCCCCC" },
	/*   149 */ { rpc__LoopSingleRocAllPixelsDacDacScan$bCSSCCCCCCCC, "LoopSingleRocAllPixelsDacDacScan$bCSSCCCCCCCC" },
	/*   150 */ { rpc__LoopSingleRocOnePixelDacDacScan$bCCCSSCCCCCC, "LoopSingleRocOnePixelDacDacScan$bCCCSSCCCCCC" },
	/*   151 */ { rpc__LoopSingleRocOnePixelDacDacScan$bCCCSSCCCCCCCC, "LoopSingleRocOnePixelDacDacScan$bCCCSSCCCCCCCC" },
	/*   152 */ { rpc__VectorTest$v1S2S, "VectorTest$v1S2S" },
	/*   153 */ { rpc__GetADC$SC, "GetADC$SC" }
};

void rpc_Dispatcher(CRpcIo &rpc_io)
{
	rpcMessage msg;
	msg.SetIo(rpc_io);
	while (true)
	{
		if (msg.RecvCmd())
		{
			uint16_t cmd = msg.GetCmd();
			if (rpc_error.HasError()) continue;
			if (cmd >= 154) continue;
			if (!rpc_cmdlist[cmd].call(msg)) msg.GetIo().Reset();
		}
	}
}
