# TCL File Generated by Component Editor 11.1sp2
# Thu May 03 12:06:24 CEST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | memport_5_16_r "memport_5_16_r" v1.0
# | Beat Meier 2012.05.03.12:06:24
# | 32 x 16 bit register file (read)
# | 
# | D:/projekte/roctest/roctest_20120208_V11_1/source/FPGA/atb/ip/memport_5_16_r/memport_5_16_r.v
# | 
# |    ./memport_5_16_r.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module memport_5_16_r
# | 
set_module_property DESCRIPTION "32 x 16 bit register file (read)"
set_module_property NAME memport_5_16_r
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP ATB
set_module_property AUTHOR "Beat Meier"
set_module_property DISPLAY_NAME memport_5_16_r
set_module_property TOP_LEVEL_HDL_FILE memport_5_16_r.v
set_module_property TOP_LEVEL_HDL_MODULE memport_5_16_r
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME memport_5_16_r
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file memport_5_16_r.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point slave
# | 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0

set_interface_property slave ENABLED true

add_interface_port slave slave_address address Input 5
add_interface_port slave slave_read read Input 1
add_interface_port slave slave_readdata readdata Output 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point register
# | 
add_interface register conduit end

set_interface_property register ENABLED true

add_interface_port register a export Output 5
add_interface_port register d export Input 16
# | 
# +-----------------------------------
