# TCL File Generated by Component Editor 12.0sp2
# Fri Apr 19 14:29:22 CEST 2013
# DO NOT MODIFY


# 
# patterngenerator "patterngenerator" v1.1
# Beat Meier 2013.04.19.14:29:22
# Pulse Pattern Generator
# 

# 
# request TCL package from ACDS 12.0
# 
package require -exact qsys 12.0


# 
# module patterngenerator
# 
set_module_property DESCRIPTION "Pulse Pattern Generator"
set_module_property NAME patterngenerator
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DTB
set_module_property AUTHOR "Beat Meier"
set_module_property DISPLAY_NAME patterngenerator
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL patterngenerator
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file patterngenerator.v VERILOG PATH patterngenerator.v
add_fileset_file pg_sequencer.v VERILOG PATH pg_sequencer.v
add_fileset_file pg_ram.v VERILOG PATH pg_ram.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock csi_clock_clk clk Input 1


# 
# connection point clock_reset
# 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock
set_interface_property clock_reset synchronousEdges DEASSERT
set_interface_property clock_reset ENABLED true

add_interface_port clock_reset csi_clock_reset reset Input 1


# 
# connection point ctrl
# 
add_interface ctrl avalon end
set_interface_property ctrl addressUnits WORDS
set_interface_property ctrl associatedClock clock
set_interface_property ctrl associatedReset clock_reset
set_interface_property ctrl bitsPerSymbol 8
set_interface_property ctrl burstOnBurstBoundariesOnly false
set_interface_property ctrl burstcountUnits WORDS
set_interface_property ctrl explicitAddressSpan 0
set_interface_property ctrl holdTime 0
set_interface_property ctrl linewrapBursts false
set_interface_property ctrl maximumPendingReadTransactions 0
set_interface_property ctrl readLatency 0
set_interface_property ctrl readWaitStates 0
set_interface_property ctrl readWaitTime 0
set_interface_property ctrl setupTime 0
set_interface_property ctrl timingUnits Cycles
set_interface_property ctrl writeWaitTime 0
set_interface_property ctrl ENABLED true

add_interface_port ctrl avs_ctrl_address address Input 1
add_interface_port ctrl avs_ctrl_read read Input 1
add_interface_port ctrl avs_ctrl_readdata readdata Output 32
add_interface_port ctrl avs_ctrl_write write Input 1
add_interface_port ctrl avs_ctrl_writedata writedata Input 32
set_interface_assignment ctrl embeddedsw.configuration.isFlash 0
set_interface_assignment ctrl embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment ctrl embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment ctrl embeddedsw.configuration.isPrintableDevice 0


# 
# connection point data
# 
add_interface data avalon end
set_interface_property data addressUnits WORDS
set_interface_property data associatedClock clock
set_interface_property data associatedReset clock_reset
set_interface_property data bitsPerSymbol 8
set_interface_property data burstOnBurstBoundariesOnly false
set_interface_property data burstcountUnits WORDS
set_interface_property data explicitAddressSpan 0
set_interface_property data holdTime 0
set_interface_property data linewrapBursts false
set_interface_property data maximumPendingReadTransactions 0
set_interface_property data readLatency 0
set_interface_property data readWaitStates 0
set_interface_property data readWaitTime 0
set_interface_property data setupTime 0
set_interface_property data timingUnits Cycles
set_interface_property data writeWaitTime 0
set_interface_property data ENABLED true

add_interface_port data avs_data_address address Input 8
add_interface_port data avs_data_write write Input 1
add_interface_port data avs_data_byteenable byteenable Input 2
add_interface_port data avs_data_writedata writedata Input 16
set_interface_assignment data embeddedsw.configuration.isFlash 0
set_interface_assignment data embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment data embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment data embeddedsw.configuration.isPrintableDevice 0


# 
# connection point pgsig
# 
add_interface pgsig conduit end
set_interface_property pgsig associatedClock clock
set_interface_property pgsig associatedReset clock_reset
set_interface_property pgsig ENABLED true

add_interface_port pgsig clkena export Input 1
add_interface_port pgsig pgout export Output 6
add_interface_port pgsig trigger export Input 1

