# TCL File Generated by Component Editor 11.1sp2
# Mon Feb 13 16:08:59 CET 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | delay_trigger "delay_trigger" v1.0
# | Beat Meier 2012.02.13.16:08:59
# | stretch pulse generator
# | 
# | D:/projekte/roctest/roctest_20120208_V11_1/source/FPGA/atb/ip/delay_trigger/delay_trigger.v
# | 
# |    ./delay_trigger.v syn, sim
# |    ./delay_trigger_core.tdf syn, sim
# |    ./dt_counter.bdf syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module delay_trigger
# | 
set_module_property DESCRIPTION "stretch pulse generator"
set_module_property NAME delay_trigger
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP ATB
set_module_property AUTHOR "Beat Meier"
set_module_property DISPLAY_NAME delay_trigger
set_module_property TOP_LEVEL_HDL_FILE delay_trigger.v
set_module_property TOP_LEVEL_HDL_MODULE delay_trigger
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME delay_trigger
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file delay_trigger.v {SYNTHESIS SIMULATION}
add_file delay_trigger_core.tdf {SYNTHESIS SIMULATION}
add_file dt_counter.bdf {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clksys clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point pulse
# | 
add_interface pulse conduit end

set_interface_property pulse ENABLED true

add_interface_port pulse sync export Input 1
add_interface_port pulse trig_in export Input 4
add_interface_port pulse pulse export Output 1
add_interface_port pulse clk export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point slave
# | 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitStates 0
set_interface_property slave readWaitTime 0
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0

set_interface_property slave ENABLED true

add_interface_port slave write write Input 1
add_interface_port slave writedata writedata Input 16
add_interface_port slave address address Input 2
# | 
# +-----------------------------------
