# TCL File Generated by Component Editor 11.1
# Tue Jun 05 12:52:25 CEST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | ft232h "FT232H" v1.0
# | Silvan Melchior 2012.06.05.12:52:25
# | USB-Controller
# | 
# | C:/FPGA_DTB/first_nios/ip/ft232h/ft232h.v
# | 
# |    ./ft232h.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module ft232h
# | 
set_module_property DESCRIPTION USB-Controller
set_module_property NAME ft232h
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Communication
set_module_property AUTHOR "Silvan Melchior"
set_module_property DISPLAY_NAME FT232H
set_module_property TOP_LEVEL_HDL_FILE ft232h.v
set_module_property TOP_LEVEL_HDL_MODULE ft232h
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME ft232h
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file ft232h.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter transmit_fifo_size INTEGER 32 "MUST be a power of 2"
set_parameter_property transmit_fifo_size DEFAULT_VALUE 32
set_parameter_property transmit_fifo_size DISPLAY_NAME transmit_fifo_size
set_parameter_property transmit_fifo_size TYPE INTEGER
set_parameter_property transmit_fifo_size UNITS None
set_parameter_property transmit_fifo_size DESCRIPTION "MUST be a power of 2"
set_parameter_property transmit_fifo_size AFFECTS_GENERATION false
set_parameter_property transmit_fifo_size HDL_PARAMETER true
add_parameter receive_fifo_size INTEGER 32 "MUST be a power of 2"
set_parameter_property receive_fifo_size DEFAULT_VALUE 32
set_parameter_property receive_fifo_size DISPLAY_NAME receive_fifo_size
set_parameter_property receive_fifo_size TYPE INTEGER
set_parameter_property receive_fifo_size UNITS None
set_parameter_property receive_fifo_size DESCRIPTION "MUST be a power of 2"
set_parameter_property receive_fifo_size AFFECTS_GENERATION false
set_parameter_property receive_fifo_size HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point ft232h
# | 
add_interface ft232h conduit end

set_interface_property ft232h ENABLED true

add_interface_port ft232h usb_siwu_n usb_siwu_n Output 1
add_interface_port ft232h usb_clk usb_clk Input 1
add_interface_port ft232h usb_oe_n usb_oe_n Output 1
add_interface_port ft232h usb_wr_n usb_wr_n Output 1
add_interface_port ft232h usb_txe_n usb_txe_n Input 1
add_interface_port ft232h usb_rd_n usb_rd_n Output 1
add_interface_port ft232h usb_rxf_n usb_rxf_n Input 1
add_interface_port ft232h usb_data usb_data Bidir 8
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitStates 0
set_interface_property avalon_slave readWaitTime 0
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0

set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave avs_slave_write write Input 1
add_interface_port avalon_slave avs_slave_read read Input 1
add_interface_port avalon_slave avs_slave_writedata writedata Input 16
add_interface_port avalon_slave avs_slave_waitrequest waitrequest Output 1
add_interface_port avalon_slave avs_slave_readdata readdata Output 16
add_interface_port avalon_slave avs_slave_address address Input 1
# | 
# +-----------------------------------
