# TCL File Generated by Component Editor 12.0sp2
# Wed Jul 10 23:09:04 CEST 2013
# DO NOT MODIFY


# 
# adc "adc" v1.0
# Beat Meier PSI 2013.07.10.23:09:04
# ADC gate
# 

# 
# request TCL package from ACDS 12.0
# 
package require -exact qsys 12.0


# 
# module adc
# 
set_module_property DESCRIPTION "ADC gate"
set_module_property NAME adc
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DTB
set_module_property AUTHOR "Beat Meier PSI"
set_module_property DISPLAY_NAME adc
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL adc
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file adc.v VERILOG PATH ip/adc/adc.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1


# 
# connection point ctrl
# 
add_interface ctrl avalon end
set_interface_property ctrl addressUnits WORDS
set_interface_property ctrl associatedClock clock
set_interface_property ctrl associatedReset reset
set_interface_property ctrl bitsPerSymbol 8
set_interface_property ctrl burstOnBurstBoundariesOnly false
set_interface_property ctrl burstcountUnits WORDS
set_interface_property ctrl explicitAddressSpan 0
set_interface_property ctrl holdTime 0
set_interface_property ctrl linewrapBursts false
set_interface_property ctrl maximumPendingReadTransactions 0
set_interface_property ctrl readLatency 0
set_interface_property ctrl readWaitStates 0
set_interface_property ctrl readWaitTime 0
set_interface_property ctrl setupTime 0
set_interface_property ctrl timingUnits Cycles
set_interface_property ctrl writeWaitTime 0
set_interface_property ctrl ENABLED true

add_interface_port ctrl address address Input 2
add_interface_port ctrl write write Input 1
add_interface_port ctrl writedata writedata Input 16
add_interface_port ctrl read read Input 1
add_interface_port ctrl readdata readdata Output 16
set_interface_assignment ctrl embeddedsw.configuration.isFlash 0
set_interface_assignment ctrl embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment ctrl embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment ctrl embeddedsw.configuration.isPrintableDevice 0


# 
# connection point adc
# 
add_interface adc conduit end
set_interface_property adc associatedClock clock
set_interface_property adc associatedReset reset
set_interface_property adc ENABLED true

add_interface_port adc adc_address export Output 2
add_interface_port adc adc_write export Output 1
add_interface_port adc adc_writedata export Output 16
add_interface_port adc adc_read export Output 1
add_interface_port adc adc_readdata export Input 16

