# TCL File Generated by Component Editor 12.0sp2
# Thu Jun 20 13:57:59 CEST 2013
# DO NOT MODIFY


# 
# daq_dma "daq_dma" v1.0
# Beat Meier PSI 2013.06.20.13:57:59
# FIFO DMA for data aquisition
# 

# 
# request TCL package from ACDS 12.0
# 
package require -exact qsys 12.0


# 
# module daq_dma
# 
set_module_property DESCRIPTION "FIFO DMA for data aquisition"
set_module_property NAME daq_dma
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DTB
set_module_property AUTHOR "Beat Meier PSI"
set_module_property DISPLAY_NAME daq_dma
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL daq_dma
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file daq_dma.v VERILOG PATH ip/daq_dma/daq_dma.v
add_fileset_file daq_dma_fifo.v VERILOG PATH ip/daq_dma/daq_dma_fifo.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1


# 
# connection point data
# 
add_interface data avalon start
set_interface_property data addressUnits SYMBOLS
set_interface_property data associatedClock clock
set_interface_property data associatedReset reset
set_interface_property data bitsPerSymbol 8
set_interface_property data burstOnBurstBoundariesOnly false
set_interface_property data burstcountUnits WORDS
set_interface_property data doStreamReads false
set_interface_property data doStreamWrites false
set_interface_property data holdTime 0
set_interface_property data linewrapBursts false
set_interface_property data maximumPendingReadTransactions 0
set_interface_property data readLatency 0
set_interface_property data readWaitTime 0
set_interface_property data setupTime 0
set_interface_property data timingUnits Cycles
set_interface_property data writeWaitTime 0
set_interface_property data ENABLED true

add_interface_port data avm_data_write write Output 1
add_interface_port data avm_data_writedata writedata Output 16
add_interface_port data avm_data_address address Output 32
add_interface_port data avm_data_byteenable byteenable Output 2
add_interface_port data avm_data_waitrq waitrequest Input 1


# 
# connection point ctrl
# 
add_interface ctrl avalon end
set_interface_property ctrl addressUnits WORDS
set_interface_property ctrl associatedClock clock
set_interface_property ctrl associatedReset reset
set_interface_property ctrl bitsPerSymbol 8
set_interface_property ctrl burstOnBurstBoundariesOnly false
set_interface_property ctrl burstcountUnits WORDS
set_interface_property ctrl explicitAddressSpan 0
set_interface_property ctrl holdTime 0
set_interface_property ctrl linewrapBursts false
set_interface_property ctrl maximumPendingReadTransactions 0
set_interface_property ctrl readLatency 0
set_interface_property ctrl readWaitStates 0
set_interface_property ctrl readWaitTime 0
set_interface_property ctrl setupTime 0
set_interface_property ctrl timingUnits Cycles
set_interface_property ctrl writeWaitTime 0
set_interface_property ctrl ENABLED true

add_interface_port ctrl avs_ctrl_write write Input 1
add_interface_port ctrl avs_ctrl_writedata writedata Input 32
add_interface_port ctrl avs_ctrl_read read Input 1
add_interface_port ctrl avs_ctrl_readdata readdata Output 32
add_interface_port ctrl avs_ctrl_address address Input 3
set_interface_assignment ctrl embeddedsw.configuration.isFlash 0
set_interface_assignment ctrl embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment ctrl embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment ctrl embeddedsw.configuration.isPrintableDevice 0


# 
# connection point daq_data
# 
add_interface daq_data conduit end
set_interface_property daq_data associatedClock ""
set_interface_property daq_data associatedReset ""
set_interface_property daq_data ENABLED true

add_interface_port daq_data write export Input 1
add_interface_port daq_data din export Input 16
add_interface_port daq_data running export Output 1
add_interface_port daq_data clk_daq export Input 1

