# TCL File Generated by Component Editor 13.1
# Tue Jul 01 13:52:56 CEST 2014
# DO NOT MODIFY


# 
# delay_in "delay_in" v1.0
# Beat Meier PSI 2014.07.01.13:52:56
# Sampling point adjust for input signal
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module delay_in
# 
set_module_property DESCRIPTION "Sampling point adjust for input signal"
set_module_property NAME delay_in
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DTB
set_module_property AUTHOR "Beat Meier PSI"
set_module_property DISPLAY_NAME delay_in
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL delay_in
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file delay_in.v VERILOG PATH ip/delay_in/delay_in.v TOP_LEVEL_FILE
add_fileset_file delay_ddrin.v VERILOG PATH ip/delay_in/delay_ddrin.v
add_fileset_file delay_in_stage.v VERILOG PATH ip/delay_in/delay_in_stage.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clock_clk clk Input 1


# 
# connection point clock_reset
# 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock
set_interface_property clock_reset synchronousEdges DEASSERT
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset csi_clock_reset reset Input 1


# 
# connection point ctrl
# 
add_interface ctrl avalon end
set_interface_property ctrl addressUnits WORDS
set_interface_property ctrl associatedClock clock
set_interface_property ctrl associatedReset clock_reset
set_interface_property ctrl bitsPerSymbol 8
set_interface_property ctrl burstOnBurstBoundariesOnly false
set_interface_property ctrl burstcountUnits WORDS
set_interface_property ctrl explicitAddressSpan 0
set_interface_property ctrl holdTime 0
set_interface_property ctrl linewrapBursts false
set_interface_property ctrl maximumPendingReadTransactions 0
set_interface_property ctrl readLatency 0
set_interface_property ctrl readWaitStates 0
set_interface_property ctrl readWaitTime 0
set_interface_property ctrl setupTime 0
set_interface_property ctrl timingUnits Cycles
set_interface_property ctrl writeWaitTime 0
set_interface_property ctrl ENABLED true
set_interface_property ctrl EXPORT_OF ""
set_interface_property ctrl PORT_NAME_MAP ""
set_interface_property ctrl CMSIS_SVD_VARIABLES ""
set_interface_property ctrl SVD_ADDRESS_GROUP ""

add_interface_port ctrl avs_ctrl_write write Input 1
add_interface_port ctrl avs_ctrl_writedata writedata Input 32
set_interface_assignment ctrl embeddedsw.configuration.isFlash 0
set_interface_assignment ctrl embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment ctrl embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment ctrl embeddedsw.configuration.isPrintableDevice 0


# 
# connection point in_delay
# 
add_interface in_delay conduit end
set_interface_property in_delay associatedClock clock
set_interface_property in_delay associatedReset clock_reset
set_interface_property in_delay ENABLED true
set_interface_property in_delay EXPORT_OF ""
set_interface_property in_delay PORT_NAME_MAP ""
set_interface_property in_delay CMSIS_SVD_VARIABLES ""
set_interface_property in_delay SVD_ADDRESS_GROUP ""

add_interface_port in_delay sync export Input 1
add_interface_port in_delay clk400 export Input 1
add_interface_port in_delay sig_out40 export Output 1
add_interface_port in_delay sig_out80 export Output 1
add_interface_port in_delay sig_in export Input 1

