# TCL File Generated by Component Editor 12.0sp2
# Wed Apr 03 11:24:22 CEST 2013
# DO NOT MODIFY


# 
# psi2c "psi2c" v1.0
# Beat Meier 2013.04.03.11:24:22
# high speed i2c
# 

# 
# request TCL package from ACDS 12.0
# 
package require -exact qsys 12.0


# 
# module psi2c
# 
set_module_property DESCRIPTION "high speed i2c"
set_module_property NAME psi2c
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DTB
set_module_property AUTHOR "Beat Meier"
set_module_property DISPLAY_NAME psi2c
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL psi2c
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file psi2c.v VERILOG PATH ip/psi2c/psi2c.v
add_fileset_file psi2c_bitsend.v VERILOG PATH ip/psi2c/psi2c_bitsend.v
add_fileset_file psi2c_control.v VERILOG PATH ip/psi2c/psi2c_control.v
add_fileset_file psi2c_fifo.v VERILOG PATH ip/psi2c/psi2c_fifo.v
add_fileset_file psi2c_readback.v VERILOG PATH ip/psi2c/psi2c_readback.v
add_fileset_file rda_bitcounter.v VERILOG PATH ip/psi2c/rda_bitcounter.v
add_fileset_file srff_timeout.v VERILOG PATH ip/psi2c/srff_timeout.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock csi_clock_clk clk Input 1


# 
# connection point ctrl
# 
add_interface ctrl avalon end
set_interface_property ctrl addressUnits WORDS
set_interface_property ctrl associatedClock clock
set_interface_property ctrl associatedReset reset
set_interface_property ctrl bitsPerSymbol 8
set_interface_property ctrl burstOnBurstBoundariesOnly false
set_interface_property ctrl burstcountUnits WORDS
set_interface_property ctrl explicitAddressSpan 0
set_interface_property ctrl holdTime 0
set_interface_property ctrl linewrapBursts false
set_interface_property ctrl maximumPendingReadTransactions 0
set_interface_property ctrl readLatency 0
set_interface_property ctrl readWaitTime 1
set_interface_property ctrl setupTime 0
set_interface_property ctrl timingUnits Cycles
set_interface_property ctrl writeWaitTime 0
set_interface_property ctrl ENABLED true

add_interface_port ctrl avs_ctrl_address address Input 3
add_interface_port ctrl avs_ctrl_read read Input 1
add_interface_port ctrl avs_ctrl_readdata readdata Output 32
add_interface_port ctrl avs_ctrl_write write Input 1
add_interface_port ctrl avs_ctrl_writedata writedata Input 32
set_interface_assignment ctrl embeddedsw.configuration.isFlash 0
set_interface_assignment ctrl embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment ctrl embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment ctrl embeddedsw.configuration.isPrintableDevice 0


# 
# connection point i2c_hs
# 
add_interface i2c_hs conduit end
set_interface_property i2c_hs associatedClock clock
set_interface_property i2c_hs associatedReset reset_sink
set_interface_property i2c_hs ENABLED true

add_interface_port i2c_hs sync export Input 1
add_interface_port i2c_hs phase export Input 1
add_interface_port i2c_hs send export Output 1
add_interface_port i2c_hs sda export Output 1
add_interface_port i2c_hs rda export Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset csi_clock_reset reset Input 1

